import { useState, useEffect } from "react";
import { get_cluster_centers, get_reports_cache_length} from "../models/fetchReportData";


//uid is the object, not the uid number itself. To access the uid number you need to do uid.uidValue as defined in fetchUids.js
export const ReportViewModel = (uidValue) => {

    //cluster_centersholds all of the cluster centers generated by each report
    const [cluster_centers, setClusterCenters] = useState([]);
    //recentClusterCenters holds only the most recent cluster centers generated by the latest report 
    const [recentClusterCenters, setRecentClusterCenter] = useState([]);
    //transformRCC makes the format of recentClusterCenters be compatible with PlotlyScatter.js
    const [transformRCC, setTransformRCC] = useState([]);
    const [loadingReport, setLoadingReport] = useState(false);

    //this holds the array of the cache length for each report 
    const[reportsCacheLength, setReportsCacheLength]=useState([]);

    useEffect(() => {

        if (!uidValue) return;

        const loadData = async () => {
            try {
                setLoadingReport(true);
                const clusterCentersResponse = await get_cluster_centers(uidValue);
                setClusterCenters(clusterCentersResponse);
                setRecentClusterCenter(clusterCentersResponse.at(-1));

                const reportsCacheLengthResponse=await get_reports_cache_length(uidValue);
                setReportsCacheLength(reportsCacheLengthResponse);
            }
            catch (error) {
                console.error(error);
            }
            finally {
                setLoadingReport(false);
            }
        }
        loadData();
    }, [uidValue]); //need to check [uidValue]



    //if a new report was generated, this useEffect will be called to transform this data so that it's compatible with PlotlyScatter
    useEffect(() => {
        if (!uidValue) return;
        const loadData = async () => {
            try {
                const data = recentClusterCenters.map((center, idx) => ({
                    x: center.map((_, i) => i + 1),  
                    y: center,
                    type: 'scatter',
                    mode: 'lines+markers',
                    name: `Cluster ${idx + 1}`,
                }));
                console.log("data is ", data);
                setTransformRCC(data);
            }
            catch (error) {
                console.error(error);
            }
        }
        loadData();
    }, [recentClusterCenters]);

    return {
        cluster_centers, recentClusterCenters, transformRCC, reportsCacheLength
    };
};