import { useState, useEffect } from "react";
import { get_cluster_centers, get_components, get_reports_cache_length } from "../models/fetchReportData";


//uid is the object, not the uid number itself. To access the uid number you need to do uid.uidValue as defined in fetchUids.js
export const ReportViewModel = (uidValue, agentType) => {

    //clusterCentersholds all of the cluster centers generated by each report
    const [clusterCenters, setClusterCenters] = useState([]);
    //recentClusterCenters holds only the most recent cluster centers generated by the latest report 
    const [recentClusterCenters, setRecentClusterCenter] = useState([]);
    //components holds all of the components generated by each report
    const [components, setComponents] = useState([]);
    //recentComponents holds only the most recent components generated by the latest report
    const [recentComponents, setRecentComponents] = useState([]);
    //transformRCC makes the format of recentClusterCenters or recentComponents be compatible with PlotlyScatter.js
    const [transformRCC, setTransformRCC] = useState([]);
    const [loadingReport, setLoadingReport] = useState(false);

    //this holds the array of the cache length for each report 
    const [reportsCacheLength, setReportsCacheLength] = useState([]);

    useEffect(() => {

        if (!uidValue) return;

        const loadData = async () => {
            try {
                setLoadingReport(true);
                if (agentType === "ClusterAgent") {
                    const clusterCentersResponse = await get_cluster_centers(uidValue);
                    setClusterCenters(clusterCentersResponse);
                    setRecentClusterCenter(clusterCentersResponse.at(-1));
                }
                else if (agentType === "DecompositionAgent") {
                    const componentsResponse = await get_components(uidValue);
                    setComponents(componentsResponse);
                    setRecentComponents(componentsResponse.at(-1));
                }
                const reportsCacheLengthResponse = await get_reports_cache_length(uidValue);
                setReportsCacheLength(reportsCacheLengthResponse);
            }
            catch (error) {
                console.error(error);
            }
            finally {
                setLoadingReport(false);
            }
        }
        loadData();
    }, [uidValue]); //need to check [uidValue]

    //if a new report was generated, this useEffect will be called to transform this data so that it's compatible with PlotlyScatter
    useEffect(() => {
        if (!uidValue) return;
        const loadData = async () => {
            try {
                if (agentType === "ClusterAgent") {
                    const data = recentClusterCenters.map((center, idx) => ({
                        x: center.map((_, i) => i + 1),
                        y: center,
                        type: 'scatter',
                        mode: 'lines+markers',
                        name: `Cluster ${idx}`,
                    }));
                    setTransformRCC(data);
                }
                else if (agentType === "DecompositionAgent") {
                    const data = recentComponents.map((center, idx) => ({
                        x: center.map((_, i) => i + 1),
                        y: center,
                        type: 'scatter',
                        mode: 'lines+markers',
                        name: `Component ${idx}`,
                    }));
                    setTransformRCC(data);
                }
            }
            catch (error) {
                console.error(error);
            }
        }
        loadData();
    }, [recentClusterCenters, recentComponents]);

    return {
        clusterCenters, recentClusterCenters,
        components, recentComponents,
        transformRCC, reportsCacheLength
    };
};